from django.db import models

# Create your models here.
class Justices(models.Model):
    name = models.TextField(blank=True, null=True)
    name_2 = models.TextField(blank=True, null=True)
    start_date = models.DateField(blank=True, null=True)
    is_active = models.TextField(blank=True, null=True)
    finish_date = models.DateField(blank=True, null=True)
    nominating_party = models.TextField(blank=True, null=True)
    military_service = models.TextField(blank=True, null=True)
    law_school = models.TextField(blank=True, null=True)
    state_of_birth = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'justices'

class Decisions(models.Model):
    caseid = models.TextField(blank=True, null=True)
    docketid = models.TextField(blank=True, null=True)
    caseissuesid = models.TextField(blank=True, null=True)
    voteid = models.TextField(blank=True, null=True)
    datedecision = models.DateField(blank=True, null=True)
    decisiontype = models.TextField(blank=True, null=True)
    uscite = models.TextField(blank=True, null=True)
    sctcite = models.TextField(blank=True, null=True)
    ledcite = models.TextField(blank=True, null=True)
    lexiscite = models.TextField(blank=True, null=True)
    term = models.IntegerField(blank=True, null=True)
    naturalcourt = models.TextField(blank=True, null=True)
    chief = models.TextField(blank=True, null=True)
    docket = models.TextField(blank=True, null=True)
    casename = models.TextField(blank=True, null=True)
    dateargument = models.DateField(blank=True, null=True)
    daterearg = models.TextField(blank=True, null=True)
    petitioner = models.TextField(blank=True, null=True)
    petitionerstate = models.TextField(blank=True, null=True)
    respondent = models.TextField(blank=True, null=True)
    respondentstate = models.TextField(blank=True, null=True)
    jurisdiction = models.TextField(blank=True, null=True)
    adminaction = models.TextField(blank=True, null=True)
    adminactionstate = models.TextField(blank=True, null=True)
    threejudgefdc = models.TextField(blank=True, null=True)
    caseorigin = models.TextField(blank=True, null=True)
    caseoriginstate = models.TextField(blank=True, null=True)
    casesource = models.TextField(blank=True, null=True)
    casesourcestate = models.TextField(blank=True, null=True)
    lcdisagreement = models.TextField(blank=True, null=True)
    certreason = models.TextField(blank=True, null=True)
    lcdisposition = models.TextField(blank=True, null=True)
    lcdispositiondirection = models.TextField(blank=True, null=True)
    declarationuncon = models.TextField(blank=True, null=True)
    casedisposition = models.TextField(blank=True, null=True)
    casedispositionunusual = models.TextField(blank=True, null=True)
    partywinning = models.TextField(blank=True, null=True)
    precedentalteration = models.TextField(blank=True, null=True)
    voteunclear = models.TextField(blank=True, null=True)
    issue = models.TextField(blank=True, null=True)
    issuearea = models.TextField(blank=True, null=True)
    decisiondirection = models.TextField(blank=True, null=True)
    decisiondirectiondissent = models.TextField(blank=True, null=True)
    authoritydecision1 = models.TextField(blank=True, null=True)
    authoritydecision2 = models.TextField(blank=True, null=True)
    lawtype = models.TextField(blank=True, null=True)
    lawsupp = models.TextField(blank=True, null=True)
    lawminor = models.TextField(blank=True, null=True)
    majopinwriter = models.TextField(blank=True, null=True)
    majopinassigner = models.TextField(blank=True, null=True)
    splitvote = models.TextField(blank=True, null=True)
    majvotes = models.IntegerField(blank=True, null=True)
    minvotes = models.IntegerField(blank=True, null=True)
    justice = models.TextField(blank=True, null=True)
    justicename = models.TextField(blank=True, null=True)
    vote = models.TextField(blank=True, null=True)
    opinion = models.TextField(blank=True, null=True)
    direction = models.TextField(blank=True, null=True)
    majority = models.TextField(blank=True, null=True)
    firstagreement = models.TextField(blank=True, null=True)
    secondagreement = models.TextField(blank=True, null=True)
    pretty_name = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'decisions'
